### ISSUE TITLE
Reptiles server crashes if $global is not passed as an option

### ISSUE THREAD

**Issue by SlashmanX** [ZJONSSON/clues#37]
After the latest update added the ability to pass `$duration`, the reptiles server will crash if `$global` is not passed as an option to clues: 

`TypeError: Cannot read property '$duration' of undefined at ../node_modules/clues/util/reptiles-server.js:104:42`

Adding a blank `$global: {}` to the reptiles parameters fixes the issue i.e. `reptiles(api, { debug:true, stringify: require('./lib/stringify'), $global: {}}));`

Caused by https://github.com/ZJONSSON/clues/blob/master/util/reptiles-server.js#L104

**Comment by ZJONSSON** [comment]
Awesome thanks @SlashmanX

**Comment by ZJONSSON** [comment]
@SlashmanX can you let me know if this fix works? https://github.com/ZJONSSON/clues/pull/38

**Comment by ZJONSSON** [comment]
published as clues@3.5.16 - please reopen if still an issue

**Comment by SlashmanX** [comment]
👍
