### ISSUE TITLE
solve() with locals doesn't override definitions properly

### ISSUE THREAD

**Issue by fzembow** [ZJONSSON/clues#6]
This is in clues@2.5.0-beta8, not sure if it is expected behavior, but I found it surprising.

Run the following:
```
var clues = require('clues');

var api = {
  A: function(B){
    return B;
  },

  B: function(C){
    return C;
  },
}

var facts = {}; 
var locals = {B: 42};

var solver = new clues(api, facts);
solver.solve(api.A, locals)
  .then(function(result){
    console.log("result", result);
  })
  .catch(function(error){
    console.log("error", error);
  });
```

The result is an error complaining that `C not defined`. But I've overridden the definition of `B`, and we should never be solving for C.

If I set
```
  facts = {B: 42};
  locals = {B: 13};
```
Then the result I get is 42. So it seems that using `locals` is broken and directly contradicts the documentation:
> The second argument (optional) allows local variables that will be used, and have priority, against facts and logic

**Comment by ZJONSSON** [comment]
Yeah I switched it around at some point without updating the documentation.  I'm on the fence on this one, it's easy to demonstrate use cases for both possibilities.  What do you think?

**Comment by fzembow** [comment]
So `locals` has no use any more? I still see `local` getting used in the source (like [here](https://github.com/ZJONSSON/clues/blob/master/clues.js#L64))...

That seems fine to remove `locals`, since we have `facts` and `.fork()`, but then `locals` should be removed from the documentation as well.

**Comment by ZJONSSON** [comment]
No what I mean is that locals are applied but as a fallback, not as a priority.    So if a particular 'name' is not found in logic/facts a local variable with same name is used (if exists)

**Comment by fzembow** [comment]
> So if a particular 'name' is not found in logic/facts a local variable with same name is used (if exists)

Ah, I see. Because `B` was defined in the logic the locals weren't being applied. I don't think that makes sense then -- because you can only use locals to overwrite leaf nodes. What was the motivation for switching the behavior?

**Comment by ZJONSSON** [comment]
I think it was a transition to "global variables" in terms of fallbacks, particularly when applied on nested structures.   Accidentally overwriting a local function with a global variable became a risk.
