### ISSUE TITLE
Merge the array-style and parameter-style args?

### ISSUE THREAD

**Issue by fzembow** [ZJONSSON/clues#9]
Consider the following:
```
var clues = require("clues");

var logic = {

  user: {
    name: "Meow Zedong",
  },

  answer: 42,

  message: ['user.name', function(name, answer) {
    return name + ", the answer is: " + answer;
  }]
};

clues(logic, 'message').then(function(res){
  console.log(res);
});
```
This results in:
```
Meow Zedong, the answer is: undefined
```

Obviously this will work as we expect if the array-style arguments also include `answer` ... but do you think that the positional arguments in the array could be extended by the arguments in the function?

I found that when using reptiles with some user input I end up seeing something like
```
var api = {
  something: ['input.A', 'B', 'C', 'D', 'E', function(a, b, c, d, e){
    ...
  }
}
```

... and it feels very verbose when it's just the first variable that needs the object resolution. Would be much nicer if it were: 
```
var api = {
  something: ['input.A', function(a, b, c, d, e){
    ...
  }
}
```

**Comment by ZJONSSON** [comment]
Excellent idea!
